name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REPO_NAME: terraform-provider-incapsula
    steps:
    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Setup env
      run: |
        export GOPATH=$HOME/go
        echo "::set-env name=GOPATH::$GOPATH"
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        mv $(pwd)/* $GOPATH/src/github.com/terraform-providers/$REPO_NAME
    - name: Test
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make test
    - name: Build
      run: |
        cd $GOPATH/src/github.com/terraform-providers/$REPO_NAME
        make build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: terraform-provider-incapsula
        path: $GOPATH/bin
